spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: helio
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
